CREATE TABLE IF NOT EXISTS shipments (
     id SERIAL PRIMARY KEY,
     shipment_number VARCHAR UNIQUE NOT NULL,
     indent_number VARCHAR,
     ifb_reference VARCHAR,
     customer_name VARCHAR,
     buyer_full_name VARCHAR,
     supplier_name VARCHAR,
     port_of_load VARCHAR,
     port_of_discharge VARCHAR,
     delivery_address VARCHAR,
     ship_on_board TIMESTAMP,
     eta TIMESTAMP,
     delivery_date TIMESTAMP,
     mv_start_date TIMESTAMP,
     mv_end_date TIMESTAMP,
     currency_code VARCHAR(3),
     order_value NUMERIC(19,4) DEFAULT 0.0000,
     shipped_value NUMERIC(19,4) DEFAULT 0.0000,
     paid_amount NUMERIC(19,4) DEFAULT 0.0000,
     unit_price NUMERIC(19,4) DEFAULT 0.0000,
     estimated_landed_cost NUMERIC(19,4) DEFAULT 0.0000,
     incoterm VARCHAR,
     status VARCHAR,
     movement_type VARCHAR,
     shipment_mode VARCHAR,
     vessel_name VARCHAR,
     container_number VARCHAR,
     container_count INTEGER DEFAULT 1,
     container_type VARCHAR,
     load_type VARCHAR,
     pallets INTEGER DEFAULT 0,
     cartons INTEGER DEFAULT 0,
     item_reference VARCHAR,
     quantity INTEGER DEFAULT 0,
     description TEXT,
     delivery_contact VARCHAR,
     delivery_month VARCHAR,
     delivery_year VARCHAR
);